name: Test
on: [push, pull_request]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ./rubocop.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}

      - name: Lint code
        run: bundle exec rubocop
  test:
    name: RSpec
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - ./gemfiles/rails_5_2.gemfile
          - ./gemfiles/rails_6_0.gemfile
          - ./gemfiles/rails_6_1.gemfile
          - ./gemfiles/rails_7_0.gemfile
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
        env:
          - DB=sqlite3
          - DB=mysql2 DB_USERNAME=root DB_PASSWORD=""
          - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
        exclude:
          - gemfile: ./gemfiles/rails_5_2.gemfile
            ruby: 3.0
          - gemfile: ./gemfiles/rails_7_0.gemfile
            ruby: 2.5
          - gemfile: ./gemfiles/rails_7_0.gemfile
            ruby: 2.6
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}
      - run: bundle exec rspec --force-color --format d
